branch-defaults:
  default:
    deploy:
      artifact: ./www/Archive.zip
    environment: udagram-ali-dev-dev
    group_suffix: null
  master:
    environment: udagram-ali-dev-dev
    group_suffix: null
global:
  application_name: udagram-ali-dev
  branch: null
  default_ec2_keyname: Udacity_KeyPair
  default_platform: Node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
